[tracked]
base_url = "http://localhost:9441"
timeout = 3.0

[versioned]
base_url = "http://localhost:9440"
timeout = 3.0

[external]
timeout = 3.0

[database]
uri = "mongodb://127.0.0.1:27017/simwatch"
