name: Build container

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and push docker container
        env:
          DOCKER_IMAGE: ${{ secrets.DOCKER_IMAGE }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_IMAGE_TAG: "1.2.1"
        run: |

          docker build -t ${DOCKER_IMAGE}:${DOCKER_IMAGE_TAG} .
          docker tag ${DOCKER_IMAGE}:${DOCKER_IMAGE_TAG} ${DOCKER_IMAGE}:latest
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push ${DOCKER_IMAGE}:${DOCKER_IMAGE_TAG}
          docker push ${DOCKER_IMAGE}:latest
